# Site settings

author: Team Hephy
email: team@teamhephy.com
maint1_mail: kingdon@teamhephy.com
maint2_mail: anton@teamhephy.com
twitter_username: teamhephy
github_username:  teamhephy
slack_inviter_url: https://slack.teamhephy.com

head-title: Team Hephy Info Blog
title: Team Hephy

baseurl: ""    # the subpath of your site, "/blog"
url: "https://blog.teamhephy.info"

# footer 
description: Hephy Workflow is the open source fork of Deis Workflow.

favo: "Open Roadmap Planning Meeting – October 2019"
descrpt: |-
  <p>Team Hephy Open Roadmap meetings are back on, after Helm Summit 2019.</p>
  <p>Team Hephy hosts community planning meetings at 2PM Eastern Time, on the first Thursday of every month. We hope you can join us at the meeting time, on Zoom. Read the post below for more info and the calendar link.</p>


#
# Build settings
#

#exclude: [vendor]

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  highlight: true
  auto_ids:  true

sass:
  style: compressed

permalink: /posts/:categories/:title.html

paginate: 7
#paginate_path: 'page/:num'

plugins: [jekyll-paginate, jekyll-last-modified-at, jemoji]


#
# Custom
#

# Color
# All css class, see: http://materializecss.com/color.html
header-color: "indigo lighten-1"
head-theme-color: "#5c6bc0"     # MUST in hex format, may the same as header-color. This color is for android chrome browser.

footer-color: "indigo lighten-1"
footer-button-color: "indigo lighten-2"
footer-link-color: "red-text text-accent-1"

share-button-color: "pink"
share-button-small-color: ""


##
#excerpt_separator: <!-- excerpt_end -->       # for post.excerpt

